### ISSUE TITLE
[BE] OAuth 테크톡 하기

### ISSUE THREAD

**Issue by ghojeong** [ghojeong/airbnb#3]
히로, 화요일 오후 4시에 OAuth 테크톡 준비해서 발표해주세요!
이거 하고, 우리 수요일날은 놀러 갑시다.

[생활코딩 Oauth 2.0](https://opentutorials.org/course/3405) 강의를 레퍼런스로 간단한 발표 준비해주세요!

참고로 Hiro 도 하니깐, 우리도 질수 없죠! 각자 공부해 옵시다.
@damilog @ha3158987

**Comment by ghojeong** [comment]
아래 용어들 및 절차들을 공부해서 발표 자료 만드시면 될것 같습니다.

- Federated Identity
- Resource Owner
- Client
- Authorization Server
- Resource Server
- accessToken

### 1. Client의 등록(Register)
  - Client ID
  - Client Secret
  - Authorized redirect URIs

### 2. Resource Owner의 승인

### 3. Resource Server 의 승인
  - authorization code
  - Location
  - code
  -  redirect_uri
  - client_id
  - client_secret
  -  accessToken

**Comment by ghojeong** [comment]
내일 테크톡에서 A 부터 G 까지, hiro 가 이해하기 쉬운 언어로 설명을 해주시면 좋을 것 같아요!

<img width="747" alt="스크린샷 2021-05-17 오후 3 43 05" src="https://user-images.githubusercontent.com/38595650/118443239-9fa59000-b726-11eb-9e1c-94061affa94f.png">

**Comment by ghojeong** [comment]
[hiro 가 힘드실까봐 제가 만든 답지 미리 준비했습니다.](https://github.com/ghojeong/playground/tree/main/oauth)

**Comment by ghojeong** [comment]
@hiro032 

작업하신 내용 정리해서 [위키에 기술 블로그글](https://github.com/ghojeong/airbnb/wiki/OAuth) 작성부탁드립니다.
테크톡 준비는 오늘 오후 4시까지 해야하지만, 기술 블로그 쓰는 일은 오늘까지만 해주시면 됩니다.
기술 블로그 쓰는데까지 완성하면 오늘 퇴근하시면 됩니다.

**Comment by hiro032** [comment]
OAuth2.0을 정리한 내용을 [노션](https://www.notion.so/OAuth-2-0-914d71b6a93f4e158c123e62474bc3f2)에 작성중 입니다.

**Comment by ghojeong** [comment]
오늘 발표한 슬라이드 자료 구글 드라이브 같은 곳에자료 올려서 링크 공유해주세요

**Comment by kyu-kim-kr** [comment]
안녕하세요 소문 듣고 왔습니다. 히로가 oauth 발표하신거 저도 보고 싶은데 링크 부탁드려요 :)

**Comment by hiro032** [comment]
@kyu-kim-kr 앗 넵 오늘이나 내일 이곳에 올려놓을게요 ㅎㅎ
