### ISSUE TITLE
[BE] 조건에 따른 조회 쿼리 작성하기

### ISSUE THREAD

**Issue by hiro032** [ghojeong/airbnb#65]
RoomRepository에 쿼리 메소드를  작성하자

**Comment by ghojeong** [comment]
ㅋㅋㅋㅋㅋ 원래 이거 내일 저녁때 쯤에 제가 이슈 만들어 드리려고 했는데, 히로가 먼저 만드셨군요.

**Comment by hiro032** [comment]
> ㅋㅋㅋㅋㅋ 원래 이거 내일 저녁때 쯤에 제가 이슈 만들어 드리려고 했는데, 히로가 먼저 만드셨군요.

브랜치 파서 쿼리좀 해보려구요 ㅋㅋ 어렵네요

**Comment by ghojeong** [comment]
참고로 다음주 스포일러 살짝 하자면,
프로젝트 구조는 충분히 잡혀있는 듯 해서, 구체적인 기능 구현은 Hiro 에게 맡기려고 했습니다.
(쿼리 짜시다가 어려운 부분은 제가 해드리는 식으로)

저는 Hiro 어려워하시는 부분 도와드리면서, ELK 학습 병행 후 Hiro 에게 알려드리려고 했고요 ㅋㅋㅋㅋ

**Comment by hiro032** [comment]
> 참고로 다음주 스포일러 살짝 하자면,
> 프로젝트 구조는 충분히 잡혀있는 듯 해서, 구체적인 기능 구현은 Hiro 에게 맡기려고 했습니다.
> (쿼리 짜시다가 어려운 부분은 제가 해드리는 식으로)
> 
> 저는 Hiro 어려워하시는 부분 도와드리면서, ELK 학습 병행 후 Hiro 에게 알려드리려고 했고요 ㅋㅋㅋㅋ
